#---------------------------------#
#      general COMPILER      #
#---------------------------------#

# version format
version: '{build}-{branch}'

# branches to build
branches:
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: false

init:
  - git config --global core.autocrlf input

clone_folder: c:\dev\libical

  #- CMAKE_GENERATOR: "Ninja"
    #PLATFORM: X86
    #COMPILER: msvc2013
  #- CMAKE_GENERATOR: "Ninja"
    #PLATFORM: X64
    #COMPILER: msvc2013
  #- CMAKE_GENERATOR: "Ninja"
    #PLATFORM: X86
    #COMPILER: msvc2015
  #- CMAKE_GENERATOR: "Ninja"
    #PLATFORM: X64
    #COMPILER: msvc2015
 #- CMAKE_GENERATOR: "Visual Studio 12"
    #PLATFORM: X86
    #COMPILER: msvc2013
  #- CMAKE_GENERATOR: "Visual Studio 12 Win64"
    #PLATFORM: X64
    #COMPILER: msvc2013
  #- CMAKE_GENERATOR: "Visual Studio 14"
    #PLATFORM: X86
    #COMPILER: msvc2015
  #- CMAKE_GENERATOR: "Visual Studio 14 Win64"
    #PLATFORM: X64
    #COMPILER: msvc2015
  #- CMAKE_GENERATOR: "NMake Makefiles JOM"
    #PLATFORM: X86
    #COMPILER: msvc2013
  #- CMAKE_GENERATOR: "NMake Makefiles JOM"
    #PLATFORM: X64
    #COMPILER: msvc2013
  #- CMAKE_GENERATOR: "NMake Makefiles JOM"
    #PLATFORM: X86
    #COMPILER: msvc2015
  #- CMAKE_GENERATOR: "NMake Makefiles JOM"
    #PLATFORM: X64
    #COMPILER: msvc2015

environment:
  matrix:
  - CMAKE_GENERATOR: "NMake Makefiles"
    PLATFORM: X86
    COMPILER: msvc2008
  - CMAKE_GENERATOR: "MinGW Makefiles"
    PLATFORM: X64
    COMPILER: MinGW

matrix:
  fast_finish: true

build_script:
  - call scripts\set_compiler_env.bat
  - cd c:\dev\libical
  - mkdir build
  - cd build
  - cmake .. -G "%CMAKE_GENERATOR%" -DGOBJECT_INTROSPECTION=False -DICAL_GLIB=False -DICAL_BUILD_DOCS=False
  - cmake --build . --config Debug
  - cmake --build . --config Release

# to disable automatic builds
#build: off

test_script:
  - cmd: ctest --output-on-failure -C "Debug"
  - cmd: ctest --output-on-failure -C "Release"

deploy: off

notifications:
  # Email
  - provider: Email
    to:
      - allen.winter@kdab.com
    on_build_status_changed: true
